export 'home_view.dart';
export 'messages_view.dart';
export 'nav_view.dart';
export 'protocol_view.dart';
export 'knowledgeView.dart';
export 'locationView.dart';
export 'reports_view.dart';
export 'testing_view_doctor.dart';
export 'testing_view_patient.dart';
