// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm6JFG7O-DdUonGKSQsstGXCAPJyHP9sw',
    appId: '1:534824954173:web:709323811c293b88d97d54',
    messagingSenderId: '534824954173',
    projectId: 'testing2-30e9e',
    authDomain: 'testing2-30e9e.firebaseapp.com',
    storageBucket: 'testing2-30e9e.appspot.com',
    measurementId: 'G-SEFV0PRC8S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADittXRVYUwrVYBCARASAMhoplfSLN0eE',
    appId: '1:534824954173:android:5a52757d9c5b53c8d97d54',
    messagingSenderId: '534824954173',
    projectId: 'testing2-30e9e',
    storageBucket: 'testing2-30e9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNJ36qKCw7r-4DJO54Ti8jOIPV3uMABmk',
    appId: '1:534824954173:ios:91447e7f9307d78fd97d54',
    messagingSenderId: '534824954173',
    projectId: 'testing2-30e9e',
    storageBucket: 'testing2-30e9e.appspot.com',
    iosClientId: '534824954173-eq38lo563slrk9g5jvcp7vvrk161mkoj.apps.googleusercontent.com',
    iosBundleId: 'none',
  );
}
